LifeRoutineCheck/LifeRoutineCheck/Views/Shared/Components/UserId/UserIdViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LifeRoutineCheck.Components.UserId
{
    public class UserIdViewComponent : ViewComponent
    {
        //Invoke()
        // ViewComponent読み込み時に実行される
        public IViewComponentResult Invoke()
        {
            return View(HttpContext.User);
        }
    }
}

LifeRoutineCheck/LifeRoutineCheck/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LifeRoutineCheck</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://fonts.googleapis.com/earlyaccess/kokoro.css" rel="stylesheet">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css" />
    <script src="//code.jquery.com/jquery-1.10.2.js"></script>
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

</head>
<body class="gradation">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul>
                        <li class="nav-item">
                            @await Component.InvokeAsync("UserId")
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div id="navArea">
        <nav>
            <div class="inner">
                <ul>
                    <li><a asp-controller="Routine" asp-action="EntryIndex" asp-area="Routine">ルーティーン登録</a></li>
                    <li><a href="#">グループ一覧</a></li>
                    <li><a href="#">友だち一覧</a></li>
                    <li><a asp-controller="Person" asp-action="UpdateUserIndex" asp-area="Person">ユーザー情報設定</a></li>
                </ul>
            </div>
        </nav>

        <div class="toggle_btn">
            <span></span>
            <span></span>
            <span></span>
        </div>

        <div id="mask">

        </div>
        <main role="main">
            @RenderBody()
        </main>
    </div>

    @*<script src="~/lib/jquery/dist/jquery.min.js"></script>*@
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>